os: osx
osx_image: xcode14.2
language: swift
script: xcodebuild clean build test -project /Users/eyupmert/Documents/EssentialDevelopers/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITIY="" CODE_SIGNING_REQUIRED=NO